### ISSUE TITLE
add address to contact entity

### ISSUE THREAD

**Issue by cedar-technologies** [skalpel-tech/skpcrm#4]
Contact models needs to have address structure.

**Comment by cedar-technologies** [comment]
couple of hints:
[Flask restplus doc](https://flask-restplus.readthedocs.io/en/stable/)
[Flask restplus model api](https://flask-restplus.readthedocs.io/en/stable/api.html#models)
[Blog on how to build restplus](http://michal.karzynski.pl/blog/2016/06/19/building-beautiful-restful-apis-using-flask-swagger-ui-flask-restplus/)

**Comment by jlaplante333** [comment]
https://www.programiz.com/article/python-self-why

**Comment by cedar-technologies** [comment]
ahah excellent

**Comment by cedar-technologies** [comment]
close in pr #8
