### ISSUE TITLE
Entity/Relations db tables design discussion

### ISSUE THREAD

**Issue by eugene-p** [skalpel-tech/skpcrm#64]
Related to #56 

Ticket to track ideas and thoughts on the data structure for models.

Here is an initial draft:

    EntityType:

        * id - entity type id
        * schema - JSON schema to be used for entity metadata validation

    Entity: 

        * id - some machine uuid
        * typeId - entity type used for validation
        * name - human readable entity id
        * content - JSON representing content

    EntityAudit:

        * entityId
        * action - CRUD
        * originalMeta

    RelationType:

        * id - Relation type id
        * fromEntity? - An entityType that can have that relationship. Can be empty for all? Can be an array? Should be part of schema?
        * toEntity? -  An entityType that can have that relationship. Can be empty for all? Can be an array? Should be part of schema?
        * schema - JSON schema to be used for Relation metadata validation

    Relation: 

        * id - some machine uuid
        * typeId - Relation type used for validation
        * fromEntity - entityLinked with relationship
        * toEntity - entityLinked with relationship
        * name - human readable Relation id
        * content - JSON representing content

    RelationAudit:

        * RelationId
        * action - CRUD
        * originalMeta

**Comment by cedar-technologies** [comment]
for

```
EntityAudit:

    * entityId
    * action - CRUD
    * originalMeta > should be originalContent for consistency
```
How would you rebuild the history of changes, by date?
I see the point of tracking read but it might grow the table, should we implement a counter instead?, too in the same audit, but maybe it's 2 different things then:
* Tracking Entity Revisions - Include Create and Update
* Tracking Entity Audit - Include CRUD

Or maybe the read counter is in the entity metadata, or maybe it's too early...

**Comment by jlaplante333** [comment]
All entities will need Activity Related data:
Last viewed Date 
Last viewed By (User)
Last modified Date
Last modified By (User)
Date created
Created by (User)
